### ISSUE TITLE
I am getting a lot of 'not found' errors when running these 2 commands (build and up)

### ISSUE THREAD

**Issue by dusantrtica** [ahmadiga/django-starterkit#2]
Hi, please help :)

I did run docker-compose build (which seems to pass OK) and then docker-compose up which spits out  a lot of 'not found' errors. (My OS: Linux Mint 18 Cinnamon 64 bit, version: 3.0.7)
Docker version 17.05.0-ce, build 89658be
docker-compose version 1.8.0, build f3628c7
Please see the output from docker-compose up.

Output (from docker-compose up)

docker-compose up
Recreating dockerbuild_celery-worker_1
Recreating dockerbuild_celery-beat_1
Recreating dockerbuild_common_server_1
Starting dockerbuild_redis_1
Recreating dockerbuild_server_1
Attaching to dockerbuild_redis_1, dockerbuild_celery-beat_1, dockerbuild_common_server_1, dockerbuild_celery-worker_1, dockerbuild_server_1
redis_1          | [1] 17 Feb 23:01:10.870 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1          |                 _._                                                  
redis_1          |            _.-``__ ''-._                                             
redis_1          |       _.-``    `.  `_.  ''-._           Redis 2.8.19 (00000000/0) 64 bit
redis_1          |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1          |  (    '      ,       .-`  | `,    )     Running in stand alone mode
redis_1          |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1          |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1          |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1          |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1          |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis_1          |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1          |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1          |  |    `-._`-._        _.-'_.-'    |                                  
redis_1          |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1          |       `-._    `-.__.-'    _.-'                                       
redis_1          |           `-._        _.-'                                           
redis_1          |               `-.__.-'                                               
redis_1          | 
redis_1          | [1] 17 Feb 23:01:10.878 # Server started, Redis version 2.8.19
redis_1          | [1] 17 Feb 23:01:10.878 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1          | [1] 17 Feb 23:01:10.878 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1          | [1] 17 Feb 23:01:10.878 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1          | [1] 17 Feb 23:01:10.879 * DB loaded from disk: 0.000 seconds
redis_1          | [1] 17 Feb 23:01:10.879 * The server is now ready to accept connections on port 6379
dockerbuild_common_server_1 exited with code 0
server_1         | python: can't open file 'manage.py': [Errno 2] No such file or directory
dockerbuild_server_1 exited with code 2
celery-beat_1    | Traceback (most recent call last):
celery-beat_1    |   File "/usr/local/bin/celery", line 11, in <module>
celery-beat_1    |     sys.exit(main())
celery-beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
celery-beat_1    |     _main()
celery-beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
celery-beat_1    |     cmd.execute_from_commandline(argv)
celery-beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
celery-beat_1    |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery-beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
celery-beat_1    |     argv = self.setup_app_from_commandline(argv)
celery-beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
celery-beat_1    |     self.app = self.find_app(app)
celery-beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 503, in find_app
celery-beat_1    |     return find_app(app, symbol_by_name=self.symbol_by_name)
celery-beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 355, in find_app
celery-beat_1    |     sym = symbol_by_name(app, imp=imp)
celery-beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 506, in symbol_by_name
celery-beat_1    |     return imports.symbol_by_name(name, imp=imp)
celery-beat_1    |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
celery-beat_1    |     module = imp(module_name, package=package, **kwargs)
celery-beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
celery-beat_1    |     return imp(module, package=package)
celery-beat_1    |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
celery-beat_1    |     return _bootstrap._gcd_import(name[level:], package, level)
celery-beat_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
celery-beat_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
celery-beat_1    |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
celery-beat_1    | ModuleNotFoundError: No module named 'django_starterkit'
dockerbuild_celery-beat_1 exited with code 1
celery-worker_1  | Traceback (most recent call last):
celery-worker_1  |   File "/usr/local/bin/celery", line 11, in <module>
celery-worker_1  |     sys.exit(main())
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
celery-worker_1  |     _main()
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
celery-worker_1  |     cmd.execute_from_commandline(argv)
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
celery-worker_1  |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
celery-worker_1  |     argv = self.setup_app_from_commandline(argv)
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
celery-worker_1  |     self.app = self.find_app(app)
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 503, in find_app
celery-worker_1  |     return find_app(app, symbol_by_name=self.symbol_by_name)
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 355, in find_app
celery-worker_1  |     sym = symbol_by_name(app, imp=imp)
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 506, in symbol_by_name
celery-worker_1  |     return imports.symbol_by_name(name, imp=imp)
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
celery-worker_1  |     module = imp(module_name, package=package, **kwargs)
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
celery-worker_1  |     return imp(module, package=package)
celery-worker_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
celery-worker_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celery-worker_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
celery-worker_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
celery-worker_1  |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
celery-worker_1  | ModuleNotFoundError: No module named 'django_starterkit'
dockerbuild_celery-worker_1 exited with code 1

**Comment by ahmadiga** [comment]
Hi
Are you using docker-machine with a VM?

**Comment by dusantrtica** [comment]
I am using docker-machine with driver set to virtualbox

**Comment by ahmadiga** [comment]
take a look at this:
https://stackoverflow.com/questions/35005974/docker-ubuntu-virtualbox-volumes-directive-in-dockerfile-not-working

**Comment by dusantrtica** [comment]
@ahmadiga Thanks a lot, this resolved my problem and saved my day!! Apparently your code works perfectly. It was wrong VM configuration on my side.
Cheers

**Comment by ahmadiga** [comment]
@dusantrtica I'm glad I could help, let me know if you need any help, + I would love to hear your feedback on the starter kit
